name: Build Pre-Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  BuildPreRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Checkout submodules
        run: git submodule update --init --recursive --force

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Update CA
        run: |
          sudo apt-get update && sudo apt-get install ca-certificates
          sudo update-ca-certificates
          cp -f /etc/ssl/certs/ca-certificates.crt core/src/foss/golang/clash/component/ca/ca-certificates.crt

      - name: Pre-release Build
        if: success()
        run: ./gradlew --no-daemon app:assembleMetaRelease

      # Delete old Prerelease-alpha
      - uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: Prerelease-alpha
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: Prerelease-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Alpha
        uses: softprops/action-gh-release@v2
        if: ${{  success() }}
        with:
          tag_name: Prerelease-alpha
          files: app/build/outputs/apk/meta/release/*
          prerelease: true
          generate_release_notes: true

      - name: Release Changelog Builder
        uses: mikepenz/release-changelog-builder-action@v4
